version: "3.3"

services:
  postgres_store:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
    # <Port exposed> : < MySQL Port running inside container>
      - "5431:5432"
